version: '3.7'

services:
  mongodb_4.4:
    restart: unless-stopped
    image : mongo:4.4 # MongoDB v4.4
    container_name: mongodb_4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: jzate
      MONGO_INITDB_ROOT_PASSWORD: jzhipster
      MONGO_INITDB_DATABASE: ate_mongodb
    volumes: # Mounts host paths or named volumes, specified as sub-options to a service.
      - /home/ate/dashboard-v2.0-data/mongodb_4.4/:/data/db
    command: [--auth]
    ports:
      - 27017:27017

  server:
    restart: unless-stopped
    container_name: server
    build:
      context: ./server/
      target: dev
    volumes:
      - ./server/:/src/
      - /src/node_modules
      - /home/ate/dashboard-v2.0-data/server/media/:/media/
    command: npm run start:dev
    ports:
      - "8080:8000"
    environment:
      NODE_ENV: dev
      DEBUG: server:*
    
  client:
    container_name: dashboard-client
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  media:
  mongodb_4.4: