GET http://localhost:8000/api/events  HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjlkNTAxZjUwNWY3MzViY2FlODc2NCIsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3RhZmYiOmZhbHNlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJ1c2VybmFtZSI6InVzZXIiLCJmaXJzdF9uYW1lIjoidXNlciIsImxhc3RfbmFtZSI6Imxhc3RfdXNlciIsImVtYWlsX2FkZHJlc3MiOiJ1c2VyQGV4YW1wbGUuY29tIiwiZGF0ZV9qb2luZWQiOjE2MjI3OTE0MjUzNDUsImlhdCI6MTYyMzAzMzA3OX0.qFMKl67t515m2tv6lvrTW1fL3i68N3xqEuKt2m0aw8w