POST http://localhost:8000/api/superuser  HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmQ4YmYxNDMwODE4MWY4MDQ3MjI4ZCIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbF9hZGRyZXNzIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpc19zdXBlcnVzZXIiOnRydWUsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3RhZmYiOnRydWUsImlhdCI6MTYyNDQxMjk0OSwiZXhwIjoxNjI0NjcyMTQ5fQ.RfLR8CJffsBPi3XQ6eLrMGKWYi5_1o0hcUShWYz2Doo