GET http://localhost:8000/api/staff  HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmQ4M2YzMjJhNmFkM2Q2NGI1MDc1OSIsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3RhZmYiOnRydWUsImlzX3N1cGVydXNlciI6ZmFsc2UsInVzZXJuYW1lIjoic3RhZmYiLCJmaXJzdF9uYW1lIjoic3RhZmYiLCJsYXN0X25hbWUiOiJsYXN0X3N0YWZmIiwiZW1haWxfYWRkcmVzcyI6InN0YWZmQGV4YW1wbGUuY29tIiwiZGF0ZV9qb2luZWQiOjE2MjMwMzI4MTk2NTcsImlhdCI6MTYyMzAzMzAxM30.wpt3vNiiC1TmiqsH6QwcLfft6NS0cjgO4-G8WzXobG0