GET http://localhost:8000/api/superuser  HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmQ4MWMwNjFmOTdkMjkwOGQ2NDcyYiIsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3RhZmYiOnRydWUsImlzX3N1cGVydXNlciI6dHJ1ZSwidXNlcm5hbWUiOiJhZG1pbiIsImZpcnN0X25hbWUiOiJhZG1pbiIsImxhc3RfbmFtZSI6Imxhc3RfYWRtaW4iLCJlbWFpbF9hZGRyZXNzIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJkYXRlX2pvaW5lZCI6MTYyMzAzMjI1Njg2MywiaWF0IjoxNjIzMDMzMDUzfQ.40ok6ZosAJRumqaUiPOoLbtwFDGNoMdus0roUpEQ3rI